### ISSUE TITLE
Добавить meta tags для соц сетей и поисковиков

### ISSUE THREAD

**Issue by lgg** [saxap/clean-wp-template#1]
OpenGraph и остальные

Могу сделать PR

**Comment by saxap** [comment]
Ну опенграф там вроде yoast seo втыкает и так.
А другую микроразметку думаю нет смысла втыкать, т.к. она узкотематическая в основном.

**Comment by lgg** [comment]
@saxap хмм, просто больше сторонних плагинов -> больше дыр + базовые meta теги можно было бы включить. Вы совсем против?

**Comment by saxap** [comment]
Да ну не совсем =)
Форкайте, посмотрим.
